"""Portable configuration, data, and lazy Torch-backed LRF-IMU exports."""

from .config import (
    DEFAULT_CONFIG_PATH,
    PACKAGE_CONFIG_DIR,
    REQUIRED_EVIDENCE_TIERS,
    ActivitySpec,
    ClassifierConfig,
    ConfigError,
    CNNConfig,
    EvidenceConfig,
    EvidenceTier,
    ExperimentConfig,
    FlowConfig,
    NormalizationConfig,
    ReleaseMetadata,
    RuntimeConfig,
    SamplingConfig,
    SensorConfig,
    SplitConfig,
    VAEConfig,
    WindowConfig,
    apply_overrides,
    load_config,
)
from .paths import FoldPaths, ProjectPaths, fold_paths, paths_from_mapping


__version__ = "1.0.0"

_VAE_EXPORTS = frozenset(
    {
        "CheckpointError",
        "CheckpointInspection",
        "LatentVAE1D",
        "TrainingResult",
        "VAEProfile",
        "augment_batch",
        "compute_vae_loss",
        "expected_state_dict_shapes",
        "inspect_vae_checkpoint",
        "load_vae_checkpoint",
        "profile_from_config",
        "save_vae_checkpoint",
        "select_vae_profile",
        "train_vae",
    }
)

_FLOW_EXPORTS = frozenset(
    {
        "EulerTrajectory",
        "FlowCheckpointError",
        "FlowCheckpointInspection",
        "FlowGenerationError",
        "FlowMatchingBatch",
        "FlowModelError",
        "FlowTrainingError",
        "FlowTrainingResult",
        "FlowUNet1D",
        "FlowWidthProfile",
        "LatentDiffusionUNet1D",
        "RectifiedFlowIMU",
        "RectifiedFlowUNet1D",
        "build_website_trajectory_payload",
        "class_labels",
        "compute_flow_loss",
        "compute_flow_matching_loss",
        "expected_flow_state_dict_shapes",
        "flow_interpolation",
        "flow_matching_batch",
        "flow_model_metadata",
        "generate_paper_latents",
        "generate_samples",
        "generate_website_trajectory",
        "inspect_flow_checkpoint",
        "interpolate_latents",
        "linear_overlap_add",
        "load_flow_checkpoint",
        "make_flow_matching_batch",
        "model_time",
        "overlap_add_windows",
        "paper_sampling_metadata",
        "profile_from_config",
        "required_segment_count",
        "reverse_euler_step",
        "sample_reverse_euler",
        "sample_reverse_euler_trajectory",
        "save_flow_checkpoint",
        "select_flow_profile",
        "sine_time_embedding",
        "train_flow",
        "website_sampling_metadata",
        "website_seed",
        "write_trajectory_payload",
    }
)

_OPTIONAL_EXPORTS = _VAE_EXPORTS | _FLOW_EXPORTS


def __getattr__(name: str):
    """Load optional Torch-backed exports only when a caller requests them."""

    if name not in _OPTIONAL_EXPORTS:
        raise AttributeError("module {!r} has no attribute {!r}".format(__name__, name))
    from .checkpoints import (
        CheckpointError,
        CheckpointInspection,
        FlowCheckpointError,
        FlowCheckpointInspection,
        expected_flow_state_dict_shapes,
        expected_state_dict_shapes,
        inspect_flow_checkpoint,
        inspect_vae_checkpoint,
        load_flow_checkpoint,
        load_vae_checkpoint,
        save_flow_checkpoint,
        save_vae_checkpoint,
    )
    from .models.flow import (
        FlowModelError,
        FlowUNet1D,
        FlowWidthProfile,
        LatentDiffusionUNet1D,
        RectifiedFlowUNet1D,
        flow_model_metadata,
        select_flow_profile,
        sine_time_embedding,
    )
    from .models.vae import LatentVAE1D
    from .training.flow import (
        FlowMatchingBatch,
        FlowTrainingError,
        FlowTrainingResult,
        RectifiedFlowIMU,
        compute_flow_loss,
        compute_flow_matching_loss,
        flow_interpolation,
        flow_matching_batch,
        interpolate_latents,
        make_flow_matching_batch,
        model_time,
        reverse_euler_step,
        train_flow,
    )
    from .training.vae import (
        TrainingResult,
        VAEProfile,
        augment_batch,
        compute_vae_loss,
        profile_from_config,
        select_vae_profile,
        train_vae,
    )
    from .generation.flow import (
        EulerTrajectory,
        FlowGenerationError,
        build_website_trajectory_payload,
        class_labels,
        generate_paper_latents,
        generate_samples,
        generate_website_trajectory,
        linear_overlap_add,
        overlap_add_windows,
        paper_sampling_metadata,
        required_segment_count,
        sample_reverse_euler,
        sample_reverse_euler_trajectory,
        website_sampling_metadata,
        website_seed,
        write_trajectory_payload,
    )
    exports = {
        "CheckpointError": CheckpointError,
        "CheckpointInspection": CheckpointInspection,
        "EulerTrajectory": EulerTrajectory,
        "FlowCheckpointError": FlowCheckpointError,
        "FlowCheckpointInspection": FlowCheckpointInspection,
        "FlowGenerationError": FlowGenerationError,
        "FlowMatchingBatch": FlowMatchingBatch,
        "FlowModelError": FlowModelError,
        "FlowTrainingError": FlowTrainingError,
        "FlowTrainingResult": FlowTrainingResult,
        "FlowUNet1D": FlowUNet1D,
        "FlowWidthProfile": FlowWidthProfile,
        "LatentDiffusionUNet1D": LatentDiffusionUNet1D,
        "LatentVAE1D": LatentVAE1D,
        "RectifiedFlowIMU": RectifiedFlowIMU,
        "RectifiedFlowUNet1D": RectifiedFlowUNet1D,
        "TrainingResult": TrainingResult,
        "VAEProfile": VAEProfile,
        "augment_batch": augment_batch,
        "build_website_trajectory_payload": build_website_trajectory_payload,
        "class_labels": class_labels,
        "compute_flow_loss": compute_flow_loss,
        "compute_flow_matching_loss": compute_flow_matching_loss,
        "compute_vae_loss": compute_vae_loss,
        "expected_flow_state_dict_shapes": expected_flow_state_dict_shapes,
        "expected_state_dict_shapes": expected_state_dict_shapes,
        "flow_interpolation": flow_interpolation,
        "flow_matching_batch": flow_matching_batch,
        "flow_model_metadata": flow_model_metadata,
        "generate_paper_latents": generate_paper_latents,
        "generate_samples": generate_samples,
        "generate_website_trajectory": generate_website_trajectory,
        "inspect_flow_checkpoint": inspect_flow_checkpoint,
        "inspect_vae_checkpoint": inspect_vae_checkpoint,
        "interpolate_latents": interpolate_latents,
        "linear_overlap_add": linear_overlap_add,
        "load_flow_checkpoint": load_flow_checkpoint,
        "load_vae_checkpoint": load_vae_checkpoint,
        "make_flow_matching_batch": make_flow_matching_batch,
        "model_time": model_time,
        "overlap_add_windows": overlap_add_windows,
        "paper_sampling_metadata": paper_sampling_metadata,
        "profile_from_config": profile_from_config,
        "required_segment_count": required_segment_count,
        "reverse_euler_step": reverse_euler_step,
        "sample_reverse_euler": sample_reverse_euler,
        "sample_reverse_euler_trajectory": sample_reverse_euler_trajectory,
        "save_flow_checkpoint": save_flow_checkpoint,
        "save_vae_checkpoint": save_vae_checkpoint,
        "select_flow_profile": select_flow_profile,
        "select_vae_profile": select_vae_profile,
        "sine_time_embedding": sine_time_embedding,
        "train_flow": train_flow,
        "train_vae": train_vae,
        "website_sampling_metadata": website_sampling_metadata,
        "website_seed": website_seed,
        "write_trajectory_payload": write_trajectory_payload,
    }
    globals().update(exports)
    return exports[name]


__all__ = [
    "ActivitySpec",
    "ClassifierConfig",
    "CheckpointError",
    "CheckpointInspection",
    "ConfigError",
    "CNNConfig",
    "DEFAULT_CONFIG_PATH",
    "EvidenceConfig",
    "PACKAGE_CONFIG_DIR",
    "EvidenceTier",
    "EulerTrajectory",
    "ExperimentConfig",
    "FlowCheckpointError",
    "FlowCheckpointInspection",
    "FlowConfig",
    "FlowGenerationError",
    "FlowMatchingBatch",
    "FlowModelError",
    "FlowTrainingError",
    "FlowTrainingResult",
    "FlowUNet1D",
    "FlowWidthProfile",
    "FoldPaths",
    "LatentDiffusionUNet1D",
    "LatentVAE1D",
    "NormalizationConfig",
    "ProjectPaths",
    "REQUIRED_EVIDENCE_TIERS",
    "RectifiedFlowIMU",
    "RectifiedFlowUNet1D",
    "ReleaseMetadata",
    "RuntimeConfig",
    "SamplingConfig",
    "SensorConfig",
    "SplitConfig",
    "TrainingResult",
    "VAEConfig",
    "VAEProfile",
    "WindowConfig",
    "apply_overrides",
    "augment_batch",
    "build_website_trajectory_payload",
    "class_labels",
    "class_labels",
    "compute_flow_loss",
    "compute_flow_matching_loss",
    "compute_vae_loss",
    "expected_flow_state_dict_shapes",
    "expected_state_dict_shapes",
    "flow_interpolation",
    "flow_matching_batch",
    "flow_model_metadata",
    "fold_paths",
    "generate_paper_latents",
    "generate_samples",
    "generate_website_trajectory",
    "inspect_flow_checkpoint",
    "inspect_vae_checkpoint",
    "interpolate_latents",
    "linear_overlap_add",
    "load_config",
    "load_flow_checkpoint",
    "load_vae_checkpoint",
    "make_flow_matching_batch",
    "model_time",
    "overlap_add_windows",
    "paper_sampling_metadata",
    "paths_from_mapping",
    "profile_from_config",
    "required_segment_count",
    "reverse_euler_step",
    "sample_reverse_euler",
    "sample_reverse_euler_trajectory",
    "save_flow_checkpoint",
    "save_vae_checkpoint",
    "select_flow_profile",
    "select_vae_profile",
    "sine_time_embedding",
    "train_flow",
    "train_vae",
    "website_sampling_metadata",
    "website_seed",
    "write_trajectory_payload",
]
